# This is a basic workflow to help you get started with Actions

name: Flutter

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.0.5'
    - run: flutter pub get
    
    - name: Lint
    - run: flutter analize --no-fatal-infos
    
    - name: Test
    - run: flutter test
    
    - name: Build android
    - run: flutter build apk
    
    - name: build ios
    - run: flutter build ios --release --no-codesign
    
    - name: Upload APK
      uses: actions/upload-artifact@v2.2.4
      with:
        name: app-release.apk
        path: build/app/outputs/flutter-apk/app-release.apk
        
  send:
    runs-on: ubuntu-latest
    steps:
      - name: send custom message with args
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: "flutter_actions: Build available"
        
